language: java
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "aamarinho"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
